### ISSUE TITLE
installation via v install vduckdb not working

### ISSUE THREAD

**Issue by b-bruno** [rodabt/vduckdb#3]
Hello,

I try to run command "v install vduckdb" and failed, see the capture.
![image](https://github.com/rodabt/vduckdb/assets/109900306/0049e577-04a0-4f26-aecb-303905867e26)

Instead I use this command "v install https://github.com/rodabt/vduckdb" and is working
![image](https://github.com/rodabt/vduckdb/assets/109900306/088681ee-b937-4792-877c-a46f824b271d)

Thanks

**Comment by rodabt** [comment]
Please try with `v install rodabt.vduckdb`

**Comment by b-bruno** [comment]
Hello,
![image](https://github.com/rodabt/vduckdb/assets/109900306/81133c5d-675a-44b7-b83d-bc3d313973d3)
Yes, it's working, thanks again for this lib for VLang :)
